// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ernado/lilith"
	"sync"
)

// Ensure, that AIMock does implement lilith.AI.
// If this is not the case, regenerate this file with moq.
var _ lilith.AI = &AIMock{}

// AIMock is a mock implementation of lilith.AI.
//
//	func TestSomethingThatUsesAI(t *testing.T) {
//
//		// make and configure a mocked lilith.AI
//		mockedAI := &AIMock{
//			DefaultModelFunc: func() string {
//				panic("mock out the DefaultModel method")
//			},
//			GenerateNotesFunc: func(ctx context.Context, existing []lilith.ChatNote, messages []lilith.Message) (string, error) {
//				panic("mock out the GenerateNotes method")
//			},
//			RespondFunc: func(ctx context.Context, req lilith.ResponseRequest) (*lilith.ResponseResult, error) {
//				panic("mock out the Respond method")
//			},
//		}
//
//		// use mockedAI in code that requires lilith.AI
//		// and then make assertions.
//
//	}
type AIMock struct {
	// DefaultModelFunc mocks the DefaultModel method.
	DefaultModelFunc func() string

	// GenerateNotesFunc mocks the GenerateNotes method.
	GenerateNotesFunc func(ctx context.Context, existing []lilith.ChatNote, messages []lilith.Message) (string, error)

	// RespondFunc mocks the Respond method.
	RespondFunc func(ctx context.Context, req lilith.ResponseRequest) (*lilith.ResponseResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// DefaultModel holds details about calls to the DefaultModel method.
		DefaultModel []struct {
		}
		// GenerateNotes holds details about calls to the GenerateNotes method.
		GenerateNotes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Existing is the existing argument value.
			Existing []lilith.ChatNote
			// Messages is the messages argument value.
			Messages []lilith.Message
		}
		// Respond holds details about calls to the Respond method.
		Respond []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req lilith.ResponseRequest
		}
	}
	lockDefaultModel  sync.RWMutex
	lockGenerateNotes sync.RWMutex
	lockRespond       sync.RWMutex
}

// DefaultModel calls DefaultModelFunc.
func (mock *AIMock) DefaultModel() string {
	if mock.DefaultModelFunc == nil {
		panic("AIMock.DefaultModelFunc: method is nil but AI.DefaultModel was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDefaultModel.Lock()
	mock.calls.DefaultModel = append(mock.calls.DefaultModel, callInfo)
	mock.lockDefaultModel.Unlock()
	return mock.DefaultModelFunc()
}

// DefaultModelCalls gets all the calls that were made to DefaultModel.
// Check the length with:
//
//	len(mockedAI.DefaultModelCalls())
func (mock *AIMock) DefaultModelCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDefaultModel.RLock()
	calls = mock.calls.DefaultModel
	mock.lockDefaultModel.RUnlock()
	return calls
}

// GenerateNotes calls GenerateNotesFunc.
func (mock *AIMock) GenerateNotes(ctx context.Context, existing []lilith.ChatNote, messages []lilith.Message) (string, error) {
	if mock.GenerateNotesFunc == nil {
		panic("AIMock.GenerateNotesFunc: method is nil but AI.GenerateNotes was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Existing []lilith.ChatNote
		Messages []lilith.Message
	}{
		Ctx:      ctx,
		Existing: existing,
		Messages: messages,
	}
	mock.lockGenerateNotes.Lock()
	mock.calls.GenerateNotes = append(mock.calls.GenerateNotes, callInfo)
	mock.lockGenerateNotes.Unlock()
	return mock.GenerateNotesFunc(ctx, existing, messages)
}

// GenerateNotesCalls gets all the calls that were made to GenerateNotes.
// Check the length with:
//
//	len(mockedAI.GenerateNotesCalls())
func (mock *AIMock) GenerateNotesCalls() []struct {
	Ctx      context.Context
	Existing []lilith.ChatNote
	Messages []lilith.Message
} {
	var calls []struct {
		Ctx      context.Context
		Existing []lilith.ChatNote
		Messages []lilith.Message
	}
	mock.lockGenerateNotes.RLock()
	calls = mock.calls.GenerateNotes
	mock.lockGenerateNotes.RUnlock()
	return calls
}

// Respond calls RespondFunc.
func (mock *AIMock) Respond(ctx context.Context, req lilith.ResponseRequest) (*lilith.ResponseResult, error) {
	if mock.RespondFunc == nil {
		panic("AIMock.RespondFunc: method is nil but AI.Respond was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req lilith.ResponseRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockRespond.Lock()
	mock.calls.Respond = append(mock.calls.Respond, callInfo)
	mock.lockRespond.Unlock()
	return mock.RespondFunc(ctx, req)
}

// RespondCalls gets all the calls that were made to Respond.
// Check the length with:
//
//	len(mockedAI.RespondCalls())
func (mock *AIMock) RespondCalls() []struct {
	Ctx context.Context
	Req lilith.ResponseRequest
} {
	var calls []struct {
		Ctx context.Context
		Req lilith.ResponseRequest
	}
	mock.lockRespond.RLock()
	calls = mock.calls.Respond
	mock.lockRespond.RUnlock()
	return calls
}
