// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ernado/lilith/internal/ai"
	"github.com/revrost/go-openrouter"
	"sync"
)

// Ensure, that ChatCompleterMock does implement ai.ChatCompleter.
// If this is not the case, regenerate this file with moq.
var _ ai.ChatCompleter = &ChatCompleterMock{}

// ChatCompleterMock is a mock implementation of ai.ChatCompleter.
//
//	func TestSomethingThatUsesChatCompleter(t *testing.T) {
//
//		// make and configure a mocked ai.ChatCompleter
//		mockedChatCompleter := &ChatCompleterMock{
//			CreateChatCompletionFunc: func(ctx context.Context, request openrouter.ChatCompletionRequest) (openrouter.ChatCompletionResponse, error) {
//				panic("mock out the CreateChatCompletion method")
//			},
//		}
//
//		// use mockedChatCompleter in code that requires ai.ChatCompleter
//		// and then make assertions.
//
//	}
type ChatCompleterMock struct {
	// CreateChatCompletionFunc mocks the CreateChatCompletion method.
	CreateChatCompletionFunc func(ctx context.Context, request openrouter.ChatCompletionRequest) (openrouter.ChatCompletionResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateChatCompletion holds details about calls to the CreateChatCompletion method.
		CreateChatCompletion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Request is the request argument value.
			Request openrouter.ChatCompletionRequest
		}
	}
	lockCreateChatCompletion sync.RWMutex
}

// CreateChatCompletion calls CreateChatCompletionFunc.
func (mock *ChatCompleterMock) CreateChatCompletion(ctx context.Context, request openrouter.ChatCompletionRequest) (openrouter.ChatCompletionResponse, error) {
	if mock.CreateChatCompletionFunc == nil {
		panic("ChatCompleterMock.CreateChatCompletionFunc: method is nil but ChatCompleter.CreateChatCompletion was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Request openrouter.ChatCompletionRequest
	}{
		Ctx:     ctx,
		Request: request,
	}
	mock.lockCreateChatCompletion.Lock()
	mock.calls.CreateChatCompletion = append(mock.calls.CreateChatCompletion, callInfo)
	mock.lockCreateChatCompletion.Unlock()
	return mock.CreateChatCompletionFunc(ctx, request)
}

// CreateChatCompletionCalls gets all the calls that were made to CreateChatCompletion.
// Check the length with:
//
//	len(mockedChatCompleter.CreateChatCompletionCalls())
func (mock *ChatCompleterMock) CreateChatCompletionCalls() []struct {
	Ctx     context.Context
	Request openrouter.ChatCompletionRequest
} {
	var calls []struct {
		Ctx     context.Context
		Request openrouter.ChatCompletionRequest
	}
	mock.lockCreateChatCompletion.RLock()
	calls = mock.calls.CreateChatCompletion
	mock.lockCreateChatCompletion.RUnlock()
	return calls
}
