// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ernado/lilith"
	"sync"
)

// Ensure, that DBMock does implement lilith.DB.
// If this is not the case, regenerate this file with moq.
var _ lilith.DB = &DBMock{}

// DBMock is a mock implementation of lilith.DB.
//
//	func TestSomethingThatUsesDB(t *testing.T) {
//
//		// make and configure a mocked lilith.DB
//		mockedDB := &DBMock{
//			AddChatNoteFunc: func(ctx context.Context, chatID int64, text string) (*lilith.ChatNote, error) {
//				panic("mock out the AddChatNote method")
//			},
//			CountMessagesSinceFunc: func(ctx context.Context, chatID int64, sinceMessageID int64, upToMessageID int64) (int64, error) {
//				panic("mock out the CountMessagesSince method")
//			},
//			DeleteMessageFunc: func(ctx context.Context, chatID int64, messageID int64) error {
//				panic("mock out the DeleteMessage method")
//			},
//			GetChatFunc: func(ctx context.Context, id int64) (*lilith.Chat, error) {
//				panic("mock out the GetChat method")
//			},
//			GetChatMemberFunc: func(ctx context.Context, chatID int64, userID int64) (*lilith.ChatMember, error) {
//				panic("mock out the GetChatMember method")
//			},
//			GetChatMembersFunc: func(ctx context.Context, chatID int64) ([]lilith.ChatMember, error) {
//				panic("mock out the GetChatMembers method")
//			},
//			GetChatNotesFunc: func(ctx context.Context, chatID int64) ([]lilith.ChatNote, error) {
//				panic("mock out the GetChatNotes method")
//			},
//			GetChatsFunc: func(ctx context.Context) ([]lilith.Chat, error) {
//				panic("mock out the GetChats method")
//			},
//			GetLastMessageFunc: func(ctx context.Context, chatID int64) (*lilith.Message, error) {
//				panic("mock out the GetLastMessage method")
//			},
//			GetLastMessageByAuthorInTopicFunc: func(ctx context.Context, chatID int64, authorID int64, messageThreadID *int64, beforeMessageID int64, lookback uint64) (*lilith.Message, error) {
//				panic("mock out the GetLastMessageByAuthorInTopic method")
//			},
//			GetLastMessagesFunc: func(ctx context.Context, chatID int64, n uint64, lastMessageID int64) ([]lilith.Message, error) {
//				panic("mock out the GetLastMessages method")
//			},
//			GetMessageFunc: func(ctx context.Context, chatID int64, messageID int64) (*lilith.Message, error) {
//				panic("mock out the GetMessage method")
//			},
//			LobotomyFunc: func(ctx context.Context, chatID int64) error {
//				panic("mock out the Lobotomy method")
//			},
//			ReplaceChatNotesFunc: func(ctx context.Context, chatID int64, text string) (*lilith.ChatNote, error) {
//				panic("mock out the ReplaceChatNotes method")
//			},
//			SaveMessageFunc: func(ctx context.Context, msg lilith.Message) error {
//				panic("mock out the SaveMessage method")
//			},
//			SetChatModelFunc: func(ctx context.Context, chatID int64, model string) error {
//				panic("mock out the SetChatModel method")
//			},
//			SetLastNotesMsgIDFunc: func(ctx context.Context, chatID int64, msgID int64) (int64, error) {
//				panic("mock out the SetLastNotesMsgID method")
//			},
//			UpsertChatFunc: func(ctx context.Context, chat lilith.Chat) error {
//				panic("mock out the UpsertChat method")
//			},
//			UpsertChatMemberFunc: func(ctx context.Context, m lilith.ChatMember) error {
//				panic("mock out the UpsertChatMember method")
//			},
//		}
//
//		// use mockedDB in code that requires lilith.DB
//		// and then make assertions.
//
//	}
type DBMock struct {
	// AddChatNoteFunc mocks the AddChatNote method.
	AddChatNoteFunc func(ctx context.Context, chatID int64, text string) (*lilith.ChatNote, error)

	// CountMessagesSinceFunc mocks the CountMessagesSince method.
	CountMessagesSinceFunc func(ctx context.Context, chatID int64, sinceMessageID int64, upToMessageID int64) (int64, error)

	// DeleteMessageFunc mocks the DeleteMessage method.
	DeleteMessageFunc func(ctx context.Context, chatID int64, messageID int64) error

	// GetChatFunc mocks the GetChat method.
	GetChatFunc func(ctx context.Context, id int64) (*lilith.Chat, error)

	// GetChatMemberFunc mocks the GetChatMember method.
	GetChatMemberFunc func(ctx context.Context, chatID int64, userID int64) (*lilith.ChatMember, error)

	// GetChatMembersFunc mocks the GetChatMembers method.
	GetChatMembersFunc func(ctx context.Context, chatID int64) ([]lilith.ChatMember, error)

	// GetChatNotesFunc mocks the GetChatNotes method.
	GetChatNotesFunc func(ctx context.Context, chatID int64) ([]lilith.ChatNote, error)

	// GetChatsFunc mocks the GetChats method.
	GetChatsFunc func(ctx context.Context) ([]lilith.Chat, error)

	// GetLastMessageFunc mocks the GetLastMessage method.
	GetLastMessageFunc func(ctx context.Context, chatID int64) (*lilith.Message, error)

	// GetLastMessageByAuthorInTopicFunc mocks the GetLastMessageByAuthorInTopic method.
	GetLastMessageByAuthorInTopicFunc func(ctx context.Context, chatID int64, authorID int64, messageThreadID *int64, beforeMessageID int64, lookback uint64) (*lilith.Message, error)

	// GetLastMessagesFunc mocks the GetLastMessages method.
	GetLastMessagesFunc func(ctx context.Context, chatID int64, n uint64, lastMessageID int64) ([]lilith.Message, error)

	// GetMessageFunc mocks the GetMessage method.
	GetMessageFunc func(ctx context.Context, chatID int64, messageID int64) (*lilith.Message, error)

	// LobotomyFunc mocks the Lobotomy method.
	LobotomyFunc func(ctx context.Context, chatID int64) error

	// ReplaceChatNotesFunc mocks the ReplaceChatNotes method.
	ReplaceChatNotesFunc func(ctx context.Context, chatID int64, text string) (*lilith.ChatNote, error)

	// SaveMessageFunc mocks the SaveMessage method.
	SaveMessageFunc func(ctx context.Context, msg lilith.Message) error

	// SetChatModelFunc mocks the SetChatModel method.
	SetChatModelFunc func(ctx context.Context, chatID int64, model string) error

	// SetLastNotesMsgIDFunc mocks the SetLastNotesMsgID method.
	SetLastNotesMsgIDFunc func(ctx context.Context, chatID int64, msgID int64) (int64, error)

	// UpsertChatFunc mocks the UpsertChat method.
	UpsertChatFunc func(ctx context.Context, chat lilith.Chat) error

	// UpsertChatMemberFunc mocks the UpsertChatMember method.
	UpsertChatMemberFunc func(ctx context.Context, m lilith.ChatMember) error

	// calls tracks calls to the methods.
	calls struct {
		// AddChatNote holds details about calls to the AddChatNote method.
		AddChatNote []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// Text is the text argument value.
			Text string
		}
		// CountMessagesSince holds details about calls to the CountMessagesSince method.
		CountMessagesSince []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// SinceMessageID is the sinceMessageID argument value.
			SinceMessageID int64
			// UpToMessageID is the upToMessageID argument value.
			UpToMessageID int64
		}
		// DeleteMessage holds details about calls to the DeleteMessage method.
		DeleteMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// MessageID is the messageID argument value.
			MessageID int64
		}
		// GetChat holds details about calls to the GetChat method.
		GetChat []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetChatMember holds details about calls to the GetChatMember method.
		GetChatMember []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// UserID is the userID argument value.
			UserID int64
		}
		// GetChatMembers holds details about calls to the GetChatMembers method.
		GetChatMembers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
		}
		// GetChatNotes holds details about calls to the GetChatNotes method.
		GetChatNotes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
		}
		// GetChats holds details about calls to the GetChats method.
		GetChats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetLastMessage holds details about calls to the GetLastMessage method.
		GetLastMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
		}
		// GetLastMessageByAuthorInTopic holds details about calls to the GetLastMessageByAuthorInTopic method.
		GetLastMessageByAuthorInTopic []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// AuthorID is the authorID argument value.
			AuthorID int64
			// MessageThreadID is the messageThreadID argument value.
			MessageThreadID *int64
			// BeforeMessageID is the beforeMessageID argument value.
			BeforeMessageID int64
			// Lookback is the lookback argument value.
			Lookback uint64
		}
		// GetLastMessages holds details about calls to the GetLastMessages method.
		GetLastMessages []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// N is the n argument value.
			N uint64
			// LastMessageID is the lastMessageID argument value.
			LastMessageID int64
		}
		// GetMessage holds details about calls to the GetMessage method.
		GetMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// MessageID is the messageID argument value.
			MessageID int64
		}
		// Lobotomy holds details about calls to the Lobotomy method.
		Lobotomy []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
		}
		// ReplaceChatNotes holds details about calls to the ReplaceChatNotes method.
		ReplaceChatNotes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// Text is the text argument value.
			Text string
		}
		// SaveMessage holds details about calls to the SaveMessage method.
		SaveMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg lilith.Message
		}
		// SetChatModel holds details about calls to the SetChatModel method.
		SetChatModel []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// Model is the model argument value.
			Model string
		}
		// SetLastNotesMsgID holds details about calls to the SetLastNotesMsgID method.
		SetLastNotesMsgID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// MsgID is the msgID argument value.
			MsgID int64
		}
		// UpsertChat holds details about calls to the UpsertChat method.
		UpsertChat []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Chat is the chat argument value.
			Chat lilith.Chat
		}
		// UpsertChatMember holds details about calls to the UpsertChatMember method.
		UpsertChatMember []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// M is the m argument value.
			M lilith.ChatMember
		}
	}
	lockAddChatNote                   sync.RWMutex
	lockCountMessagesSince            sync.RWMutex
	lockDeleteMessage                 sync.RWMutex
	lockGetChat                       sync.RWMutex
	lockGetChatMember                 sync.RWMutex
	lockGetChatMembers                sync.RWMutex
	lockGetChatNotes                  sync.RWMutex
	lockGetChats                      sync.RWMutex
	lockGetLastMessage                sync.RWMutex
	lockGetLastMessageByAuthorInTopic sync.RWMutex
	lockGetLastMessages               sync.RWMutex
	lockGetMessage                    sync.RWMutex
	lockLobotomy                      sync.RWMutex
	lockReplaceChatNotes              sync.RWMutex
	lockSaveMessage                   sync.RWMutex
	lockSetChatModel                  sync.RWMutex
	lockSetLastNotesMsgID             sync.RWMutex
	lockUpsertChat                    sync.RWMutex
	lockUpsertChatMember              sync.RWMutex
}

// AddChatNote calls AddChatNoteFunc.
func (mock *DBMock) AddChatNote(ctx context.Context, chatID int64, text string) (*lilith.ChatNote, error) {
	if mock.AddChatNoteFunc == nil {
		panic("DBMock.AddChatNoteFunc: method is nil but DB.AddChatNote was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ChatID int64
		Text   string
	}{
		Ctx:    ctx,
		ChatID: chatID,
		Text:   text,
	}
	mock.lockAddChatNote.Lock()
	mock.calls.AddChatNote = append(mock.calls.AddChatNote, callInfo)
	mock.lockAddChatNote.Unlock()
	return mock.AddChatNoteFunc(ctx, chatID, text)
}

// AddChatNoteCalls gets all the calls that were made to AddChatNote.
// Check the length with:
//
//	len(mockedDB.AddChatNoteCalls())
func (mock *DBMock) AddChatNoteCalls() []struct {
	Ctx    context.Context
	ChatID int64
	Text   string
} {
	var calls []struct {
		Ctx    context.Context
		ChatID int64
		Text   string
	}
	mock.lockAddChatNote.RLock()
	calls = mock.calls.AddChatNote
	mock.lockAddChatNote.RUnlock()
	return calls
}

// CountMessagesSince calls CountMessagesSinceFunc.
func (mock *DBMock) CountMessagesSince(ctx context.Context, chatID int64, sinceMessageID int64, upToMessageID int64) (int64, error) {
	if mock.CountMessagesSinceFunc == nil {
		panic("DBMock.CountMessagesSinceFunc: method is nil but DB.CountMessagesSince was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		ChatID         int64
		SinceMessageID int64
		UpToMessageID  int64
	}{
		Ctx:            ctx,
		ChatID:         chatID,
		SinceMessageID: sinceMessageID,
		UpToMessageID:  upToMessageID,
	}
	mock.lockCountMessagesSince.Lock()
	mock.calls.CountMessagesSince = append(mock.calls.CountMessagesSince, callInfo)
	mock.lockCountMessagesSince.Unlock()
	return mock.CountMessagesSinceFunc(ctx, chatID, sinceMessageID, upToMessageID)
}

// CountMessagesSinceCalls gets all the calls that were made to CountMessagesSince.
// Check the length with:
//
//	len(mockedDB.CountMessagesSinceCalls())
func (mock *DBMock) CountMessagesSinceCalls() []struct {
	Ctx            context.Context
	ChatID         int64
	SinceMessageID int64
	UpToMessageID  int64
} {
	var calls []struct {
		Ctx            context.Context
		ChatID         int64
		SinceMessageID int64
		UpToMessageID  int64
	}
	mock.lockCountMessagesSince.RLock()
	calls = mock.calls.CountMessagesSince
	mock.lockCountMessagesSince.RUnlock()
	return calls
}

// DeleteMessage calls DeleteMessageFunc.
func (mock *DBMock) DeleteMessage(ctx context.Context, chatID int64, messageID int64) error {
	if mock.DeleteMessageFunc == nil {
		panic("DBMock.DeleteMessageFunc: method is nil but DB.DeleteMessage was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ChatID    int64
		MessageID int64
	}{
		Ctx:       ctx,
		ChatID:    chatID,
		MessageID: messageID,
	}
	mock.lockDeleteMessage.Lock()
	mock.calls.DeleteMessage = append(mock.calls.DeleteMessage, callInfo)
	mock.lockDeleteMessage.Unlock()
	return mock.DeleteMessageFunc(ctx, chatID, messageID)
}

// DeleteMessageCalls gets all the calls that were made to DeleteMessage.
// Check the length with:
//
//	len(mockedDB.DeleteMessageCalls())
func (mock *DBMock) DeleteMessageCalls() []struct {
	Ctx       context.Context
	ChatID    int64
	MessageID int64
} {
	var calls []struct {
		Ctx       context.Context
		ChatID    int64
		MessageID int64
	}
	mock.lockDeleteMessage.RLock()
	calls = mock.calls.DeleteMessage
	mock.lockDeleteMessage.RUnlock()
	return calls
}

// GetChat calls GetChatFunc.
func (mock *DBMock) GetChat(ctx context.Context, id int64) (*lilith.Chat, error) {
	if mock.GetChatFunc == nil {
		panic("DBMock.GetChatFunc: method is nil but DB.GetChat was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetChat.Lock()
	mock.calls.GetChat = append(mock.calls.GetChat, callInfo)
	mock.lockGetChat.Unlock()
	return mock.GetChatFunc(ctx, id)
}

// GetChatCalls gets all the calls that were made to GetChat.
// Check the length with:
//
//	len(mockedDB.GetChatCalls())
func (mock *DBMock) GetChatCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetChat.RLock()
	calls = mock.calls.GetChat
	mock.lockGetChat.RUnlock()
	return calls
}

// GetChatMember calls GetChatMemberFunc.
func (mock *DBMock) GetChatMember(ctx context.Context, chatID int64, userID int64) (*lilith.ChatMember, error) {
	if mock.GetChatMemberFunc == nil {
		panic("DBMock.GetChatMemberFunc: method is nil but DB.GetChatMember was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ChatID int64
		UserID int64
	}{
		Ctx:    ctx,
		ChatID: chatID,
		UserID: userID,
	}
	mock.lockGetChatMember.Lock()
	mock.calls.GetChatMember = append(mock.calls.GetChatMember, callInfo)
	mock.lockGetChatMember.Unlock()
	return mock.GetChatMemberFunc(ctx, chatID, userID)
}

// GetChatMemberCalls gets all the calls that were made to GetChatMember.
// Check the length with:
//
//	len(mockedDB.GetChatMemberCalls())
func (mock *DBMock) GetChatMemberCalls() []struct {
	Ctx    context.Context
	ChatID int64
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		ChatID int64
		UserID int64
	}
	mock.lockGetChatMember.RLock()
	calls = mock.calls.GetChatMember
	mock.lockGetChatMember.RUnlock()
	return calls
}

// GetChatMembers calls GetChatMembersFunc.
func (mock *DBMock) GetChatMembers(ctx context.Context, chatID int64) ([]lilith.ChatMember, error) {
	if mock.GetChatMembersFunc == nil {
		panic("DBMock.GetChatMembersFunc: method is nil but DB.GetChatMembers was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ChatID int64
	}{
		Ctx:    ctx,
		ChatID: chatID,
	}
	mock.lockGetChatMembers.Lock()
	mock.calls.GetChatMembers = append(mock.calls.GetChatMembers, callInfo)
	mock.lockGetChatMembers.Unlock()
	return mock.GetChatMembersFunc(ctx, chatID)
}

// GetChatMembersCalls gets all the calls that were made to GetChatMembers.
// Check the length with:
//
//	len(mockedDB.GetChatMembersCalls())
func (mock *DBMock) GetChatMembersCalls() []struct {
	Ctx    context.Context
	ChatID int64
} {
	var calls []struct {
		Ctx    context.Context
		ChatID int64
	}
	mock.lockGetChatMembers.RLock()
	calls = mock.calls.GetChatMembers
	mock.lockGetChatMembers.RUnlock()
	return calls
}

// GetChatNotes calls GetChatNotesFunc.
func (mock *DBMock) GetChatNotes(ctx context.Context, chatID int64) ([]lilith.ChatNote, error) {
	if mock.GetChatNotesFunc == nil {
		panic("DBMock.GetChatNotesFunc: method is nil but DB.GetChatNotes was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ChatID int64
	}{
		Ctx:    ctx,
		ChatID: chatID,
	}
	mock.lockGetChatNotes.Lock()
	mock.calls.GetChatNotes = append(mock.calls.GetChatNotes, callInfo)
	mock.lockGetChatNotes.Unlock()
	return mock.GetChatNotesFunc(ctx, chatID)
}

// GetChatNotesCalls gets all the calls that were made to GetChatNotes.
// Check the length with:
//
//	len(mockedDB.GetChatNotesCalls())
func (mock *DBMock) GetChatNotesCalls() []struct {
	Ctx    context.Context
	ChatID int64
} {
	var calls []struct {
		Ctx    context.Context
		ChatID int64
	}
	mock.lockGetChatNotes.RLock()
	calls = mock.calls.GetChatNotes
	mock.lockGetChatNotes.RUnlock()
	return calls
}

// GetChats calls GetChatsFunc.
func (mock *DBMock) GetChats(ctx context.Context) ([]lilith.Chat, error) {
	if mock.GetChatsFunc == nil {
		panic("DBMock.GetChatsFunc: method is nil but DB.GetChats was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetChats.Lock()
	mock.calls.GetChats = append(mock.calls.GetChats, callInfo)
	mock.lockGetChats.Unlock()
	return mock.GetChatsFunc(ctx)
}

// GetChatsCalls gets all the calls that were made to GetChats.
// Check the length with:
//
//	len(mockedDB.GetChatsCalls())
func (mock *DBMock) GetChatsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetChats.RLock()
	calls = mock.calls.GetChats
	mock.lockGetChats.RUnlock()
	return calls
}

// GetLastMessage calls GetLastMessageFunc.
func (mock *DBMock) GetLastMessage(ctx context.Context, chatID int64) (*lilith.Message, error) {
	if mock.GetLastMessageFunc == nil {
		panic("DBMock.GetLastMessageFunc: method is nil but DB.GetLastMessage was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ChatID int64
	}{
		Ctx:    ctx,
		ChatID: chatID,
	}
	mock.lockGetLastMessage.Lock()
	mock.calls.GetLastMessage = append(mock.calls.GetLastMessage, callInfo)
	mock.lockGetLastMessage.Unlock()
	return mock.GetLastMessageFunc(ctx, chatID)
}

// GetLastMessageCalls gets all the calls that were made to GetLastMessage.
// Check the length with:
//
//	len(mockedDB.GetLastMessageCalls())
func (mock *DBMock) GetLastMessageCalls() []struct {
	Ctx    context.Context
	ChatID int64
} {
	var calls []struct {
		Ctx    context.Context
		ChatID int64
	}
	mock.lockGetLastMessage.RLock()
	calls = mock.calls.GetLastMessage
	mock.lockGetLastMessage.RUnlock()
	return calls
}

// GetLastMessageByAuthorInTopic calls GetLastMessageByAuthorInTopicFunc.
func (mock *DBMock) GetLastMessageByAuthorInTopic(ctx context.Context, chatID int64, authorID int64, messageThreadID *int64, beforeMessageID int64, lookback uint64) (*lilith.Message, error) {
	if mock.GetLastMessageByAuthorInTopicFunc == nil {
		panic("DBMock.GetLastMessageByAuthorInTopicFunc: method is nil but DB.GetLastMessageByAuthorInTopic was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		ChatID          int64
		AuthorID        int64
		MessageThreadID *int64
		BeforeMessageID int64
		Lookback        uint64
	}{
		Ctx:             ctx,
		ChatID:          chatID,
		AuthorID:        authorID,
		MessageThreadID: messageThreadID,
		BeforeMessageID: beforeMessageID,
		Lookback:        lookback,
	}
	mock.lockGetLastMessageByAuthorInTopic.Lock()
	mock.calls.GetLastMessageByAuthorInTopic = append(mock.calls.GetLastMessageByAuthorInTopic, callInfo)
	mock.lockGetLastMessageByAuthorInTopic.Unlock()
	return mock.GetLastMessageByAuthorInTopicFunc(ctx, chatID, authorID, messageThreadID, beforeMessageID, lookback)
}

// GetLastMessageByAuthorInTopicCalls gets all the calls that were made to GetLastMessageByAuthorInTopic.
// Check the length with:
//
//	len(mockedDB.GetLastMessageByAuthorInTopicCalls())
func (mock *DBMock) GetLastMessageByAuthorInTopicCalls() []struct {
	Ctx             context.Context
	ChatID          int64
	AuthorID        int64
	MessageThreadID *int64
	BeforeMessageID int64
	Lookback        uint64
} {
	var calls []struct {
		Ctx             context.Context
		ChatID          int64
		AuthorID        int64
		MessageThreadID *int64
		BeforeMessageID int64
		Lookback        uint64
	}
	mock.lockGetLastMessageByAuthorInTopic.RLock()
	calls = mock.calls.GetLastMessageByAuthorInTopic
	mock.lockGetLastMessageByAuthorInTopic.RUnlock()
	return calls
}

// GetLastMessages calls GetLastMessagesFunc.
func (mock *DBMock) GetLastMessages(ctx context.Context, chatID int64, n uint64, lastMessageID int64) ([]lilith.Message, error) {
	if mock.GetLastMessagesFunc == nil {
		panic("DBMock.GetLastMessagesFunc: method is nil but DB.GetLastMessages was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ChatID        int64
		N             uint64
		LastMessageID int64
	}{
		Ctx:           ctx,
		ChatID:        chatID,
		N:             n,
		LastMessageID: lastMessageID,
	}
	mock.lockGetLastMessages.Lock()
	mock.calls.GetLastMessages = append(mock.calls.GetLastMessages, callInfo)
	mock.lockGetLastMessages.Unlock()
	return mock.GetLastMessagesFunc(ctx, chatID, n, lastMessageID)
}

// GetLastMessagesCalls gets all the calls that were made to GetLastMessages.
// Check the length with:
//
//	len(mockedDB.GetLastMessagesCalls())
func (mock *DBMock) GetLastMessagesCalls() []struct {
	Ctx           context.Context
	ChatID        int64
	N             uint64
	LastMessageID int64
} {
	var calls []struct {
		Ctx           context.Context
		ChatID        int64
		N             uint64
		LastMessageID int64
	}
	mock.lockGetLastMessages.RLock()
	calls = mock.calls.GetLastMessages
	mock.lockGetLastMessages.RUnlock()
	return calls
}

// GetMessage calls GetMessageFunc.
func (mock *DBMock) GetMessage(ctx context.Context, chatID int64, messageID int64) (*lilith.Message, error) {
	if mock.GetMessageFunc == nil {
		panic("DBMock.GetMessageFunc: method is nil but DB.GetMessage was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ChatID    int64
		MessageID int64
	}{
		Ctx:       ctx,
		ChatID:    chatID,
		MessageID: messageID,
	}
	mock.lockGetMessage.Lock()
	mock.calls.GetMessage = append(mock.calls.GetMessage, callInfo)
	mock.lockGetMessage.Unlock()
	return mock.GetMessageFunc(ctx, chatID, messageID)
}

// GetMessageCalls gets all the calls that were made to GetMessage.
// Check the length with:
//
//	len(mockedDB.GetMessageCalls())
func (mock *DBMock) GetMessageCalls() []struct {
	Ctx       context.Context
	ChatID    int64
	MessageID int64
} {
	var calls []struct {
		Ctx       context.Context
		ChatID    int64
		MessageID int64
	}
	mock.lockGetMessage.RLock()
	calls = mock.calls.GetMessage
	mock.lockGetMessage.RUnlock()
	return calls
}

// Lobotomy calls LobotomyFunc.
func (mock *DBMock) Lobotomy(ctx context.Context, chatID int64) error {
	if mock.LobotomyFunc == nil {
		panic("DBMock.LobotomyFunc: method is nil but DB.Lobotomy was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ChatID int64
	}{
		Ctx:    ctx,
		ChatID: chatID,
	}
	mock.lockLobotomy.Lock()
	mock.calls.Lobotomy = append(mock.calls.Lobotomy, callInfo)
	mock.lockLobotomy.Unlock()
	return mock.LobotomyFunc(ctx, chatID)
}

// LobotomyCalls gets all the calls that were made to Lobotomy.
// Check the length with:
//
//	len(mockedDB.LobotomyCalls())
func (mock *DBMock) LobotomyCalls() []struct {
	Ctx    context.Context
	ChatID int64
} {
	var calls []struct {
		Ctx    context.Context
		ChatID int64
	}
	mock.lockLobotomy.RLock()
	calls = mock.calls.Lobotomy
	mock.lockLobotomy.RUnlock()
	return calls
}

// ReplaceChatNotes calls ReplaceChatNotesFunc.
func (mock *DBMock) ReplaceChatNotes(ctx context.Context, chatID int64, text string) (*lilith.ChatNote, error) {
	if mock.ReplaceChatNotesFunc == nil {
		panic("DBMock.ReplaceChatNotesFunc: method is nil but DB.ReplaceChatNotes was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ChatID int64
		Text   string
	}{
		Ctx:    ctx,
		ChatID: chatID,
		Text:   text,
	}
	mock.lockReplaceChatNotes.Lock()
	mock.calls.ReplaceChatNotes = append(mock.calls.ReplaceChatNotes, callInfo)
	mock.lockReplaceChatNotes.Unlock()
	return mock.ReplaceChatNotesFunc(ctx, chatID, text)
}

// ReplaceChatNotesCalls gets all the calls that were made to ReplaceChatNotes.
// Check the length with:
//
//	len(mockedDB.ReplaceChatNotesCalls())
func (mock *DBMock) ReplaceChatNotesCalls() []struct {
	Ctx    context.Context
	ChatID int64
	Text   string
} {
	var calls []struct {
		Ctx    context.Context
		ChatID int64
		Text   string
	}
	mock.lockReplaceChatNotes.RLock()
	calls = mock.calls.ReplaceChatNotes
	mock.lockReplaceChatNotes.RUnlock()
	return calls
}

// SaveMessage calls SaveMessageFunc.
func (mock *DBMock) SaveMessage(ctx context.Context, msg lilith.Message) error {
	if mock.SaveMessageFunc == nil {
		panic("DBMock.SaveMessageFunc: method is nil but DB.SaveMessage was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Msg lilith.Message
	}{
		Ctx: ctx,
		Msg: msg,
	}
	mock.lockSaveMessage.Lock()
	mock.calls.SaveMessage = append(mock.calls.SaveMessage, callInfo)
	mock.lockSaveMessage.Unlock()
	return mock.SaveMessageFunc(ctx, msg)
}

// SaveMessageCalls gets all the calls that were made to SaveMessage.
// Check the length with:
//
//	len(mockedDB.SaveMessageCalls())
func (mock *DBMock) SaveMessageCalls() []struct {
	Ctx context.Context
	Msg lilith.Message
} {
	var calls []struct {
		Ctx context.Context
		Msg lilith.Message
	}
	mock.lockSaveMessage.RLock()
	calls = mock.calls.SaveMessage
	mock.lockSaveMessage.RUnlock()
	return calls
}

// SetChatModel calls SetChatModelFunc.
func (mock *DBMock) SetChatModel(ctx context.Context, chatID int64, model string) error {
	if mock.SetChatModelFunc == nil {
		panic("DBMock.SetChatModelFunc: method is nil but DB.SetChatModel was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ChatID int64
		Model  string
	}{
		Ctx:    ctx,
		ChatID: chatID,
		Model:  model,
	}
	mock.lockSetChatModel.Lock()
	mock.calls.SetChatModel = append(mock.calls.SetChatModel, callInfo)
	mock.lockSetChatModel.Unlock()
	return mock.SetChatModelFunc(ctx, chatID, model)
}

// SetChatModelCalls gets all the calls that were made to SetChatModel.
// Check the length with:
//
//	len(mockedDB.SetChatModelCalls())
func (mock *DBMock) SetChatModelCalls() []struct {
	Ctx    context.Context
	ChatID int64
	Model  string
} {
	var calls []struct {
		Ctx    context.Context
		ChatID int64
		Model  string
	}
	mock.lockSetChatModel.RLock()
	calls = mock.calls.SetChatModel
	mock.lockSetChatModel.RUnlock()
	return calls
}

// SetLastNotesMsgID calls SetLastNotesMsgIDFunc.
func (mock *DBMock) SetLastNotesMsgID(ctx context.Context, chatID int64, msgID int64) (int64, error) {
	if mock.SetLastNotesMsgIDFunc == nil {
		panic("DBMock.SetLastNotesMsgIDFunc: method is nil but DB.SetLastNotesMsgID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ChatID int64
		MsgID  int64
	}{
		Ctx:    ctx,
		ChatID: chatID,
		MsgID:  msgID,
	}
	mock.lockSetLastNotesMsgID.Lock()
	mock.calls.SetLastNotesMsgID = append(mock.calls.SetLastNotesMsgID, callInfo)
	mock.lockSetLastNotesMsgID.Unlock()
	return mock.SetLastNotesMsgIDFunc(ctx, chatID, msgID)
}

// SetLastNotesMsgIDCalls gets all the calls that were made to SetLastNotesMsgID.
// Check the length with:
//
//	len(mockedDB.SetLastNotesMsgIDCalls())
func (mock *DBMock) SetLastNotesMsgIDCalls() []struct {
	Ctx    context.Context
	ChatID int64
	MsgID  int64
} {
	var calls []struct {
		Ctx    context.Context
		ChatID int64
		MsgID  int64
	}
	mock.lockSetLastNotesMsgID.RLock()
	calls = mock.calls.SetLastNotesMsgID
	mock.lockSetLastNotesMsgID.RUnlock()
	return calls
}

// UpsertChat calls UpsertChatFunc.
func (mock *DBMock) UpsertChat(ctx context.Context, chat lilith.Chat) error {
	if mock.UpsertChatFunc == nil {
		panic("DBMock.UpsertChatFunc: method is nil but DB.UpsertChat was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Chat lilith.Chat
	}{
		Ctx:  ctx,
		Chat: chat,
	}
	mock.lockUpsertChat.Lock()
	mock.calls.UpsertChat = append(mock.calls.UpsertChat, callInfo)
	mock.lockUpsertChat.Unlock()
	return mock.UpsertChatFunc(ctx, chat)
}

// UpsertChatCalls gets all the calls that were made to UpsertChat.
// Check the length with:
//
//	len(mockedDB.UpsertChatCalls())
func (mock *DBMock) UpsertChatCalls() []struct {
	Ctx  context.Context
	Chat lilith.Chat
} {
	var calls []struct {
		Ctx  context.Context
		Chat lilith.Chat
	}
	mock.lockUpsertChat.RLock()
	calls = mock.calls.UpsertChat
	mock.lockUpsertChat.RUnlock()
	return calls
}

// UpsertChatMember calls UpsertChatMemberFunc.
func (mock *DBMock) UpsertChatMember(ctx context.Context, m lilith.ChatMember) error {
	if mock.UpsertChatMemberFunc == nil {
		panic("DBMock.UpsertChatMemberFunc: method is nil but DB.UpsertChatMember was just called")
	}
	callInfo := struct {
		Ctx context.Context
		M   lilith.ChatMember
	}{
		Ctx: ctx,
		M:   m,
	}
	mock.lockUpsertChatMember.Lock()
	mock.calls.UpsertChatMember = append(mock.calls.UpsertChatMember, callInfo)
	mock.lockUpsertChatMember.Unlock()
	return mock.UpsertChatMemberFunc(ctx, m)
}

// UpsertChatMemberCalls gets all the calls that were made to UpsertChatMember.
// Check the length with:
//
//	len(mockedDB.UpsertChatMemberCalls())
func (mock *DBMock) UpsertChatMemberCalls() []struct {
	Ctx context.Context
	M   lilith.ChatMember
} {
	var calls []struct {
		Ctx context.Context
		M   lilith.ChatMember
	}
	mock.lockUpsertChatMember.RLock()
	calls = mock.calls.UpsertChatMember
	mock.lockUpsertChatMember.RUnlock()
	return calls
}
