// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ernado/lilith"
	"sync"
)

// Ensure, that DiscordProviderMock does implement lilith.DiscordProvider.
// If this is not the case, regenerate this file with moq.
var _ lilith.DiscordProvider = &DiscordProviderMock{}

// DiscordProviderMock is a mock implementation of lilith.DiscordProvider.
//
//	func TestSomethingThatUsesDiscordProvider(t *testing.T) {
//
//		// make and configure a mocked lilith.DiscordProvider
//		mockedDiscordProvider := &DiscordProviderMock{
//			PopulatedChannelsFunc: func(ctx context.Context) ([]lilith.DiscordChannel, error) {
//				panic("mock out the PopulatedChannels method")
//			},
//		}
//
//		// use mockedDiscordProvider in code that requires lilith.DiscordProvider
//		// and then make assertions.
//
//	}
type DiscordProviderMock struct {
	// PopulatedChannelsFunc mocks the PopulatedChannels method.
	PopulatedChannelsFunc func(ctx context.Context) ([]lilith.DiscordChannel, error)

	// calls tracks calls to the methods.
	calls struct {
		// PopulatedChannels holds details about calls to the PopulatedChannels method.
		PopulatedChannels []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockPopulatedChannels sync.RWMutex
}

// PopulatedChannels calls PopulatedChannelsFunc.
func (mock *DiscordProviderMock) PopulatedChannels(ctx context.Context) ([]lilith.DiscordChannel, error) {
	if mock.PopulatedChannelsFunc == nil {
		panic("DiscordProviderMock.PopulatedChannelsFunc: method is nil but DiscordProvider.PopulatedChannels was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPopulatedChannels.Lock()
	mock.calls.PopulatedChannels = append(mock.calls.PopulatedChannels, callInfo)
	mock.lockPopulatedChannels.Unlock()
	return mock.PopulatedChannelsFunc(ctx)
}

// PopulatedChannelsCalls gets all the calls that were made to PopulatedChannels.
// Check the length with:
//
//	len(mockedDiscordProvider.PopulatedChannelsCalls())
func (mock *DiscordProviderMock) PopulatedChannelsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPopulatedChannels.RLock()
	calls = mock.calls.PopulatedChannels
	mock.lockPopulatedChannels.RUnlock()
	return calls
}
