// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/ernado/lilith"
	"io"
	"sync"
)

// Ensure, that FileStoreMock does implement lilith.FileStore.
// If this is not the case, regenerate this file with moq.
var _ lilith.FileStore = &FileStoreMock{}

// FileStoreMock is a mock implementation of lilith.FileStore.
//
//	func TestSomethingThatUsesFileStore(t *testing.T) {
//
//		// make and configure a mocked lilith.FileStore
//		mockedFileStore := &FileStoreMock{
//			DeleteFunc: func(url string) error {
//				panic("mock out the Delete method")
//			},
//			UploadFunc: func(r io.Reader) (string, error) {
//				panic("mock out the Upload method")
//			},
//		}
//
//		// use mockedFileStore in code that requires lilith.FileStore
//		// and then make assertions.
//
//	}
type FileStoreMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(url string) error

	// UploadFunc mocks the Upload method.
	UploadFunc func(r io.Reader) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// URL is the url argument value.
			URL string
		}
		// Upload holds details about calls to the Upload method.
		Upload []struct {
			// R is the r argument value.
			R io.Reader
		}
	}
	lockDelete sync.RWMutex
	lockUpload sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *FileStoreMock) Delete(url string) error {
	if mock.DeleteFunc == nil {
		panic("FileStoreMock.DeleteFunc: method is nil but FileStore.Delete was just called")
	}
	callInfo := struct {
		URL string
	}{
		URL: url,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(url)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedFileStore.DeleteCalls())
func (mock *FileStoreMock) DeleteCalls() []struct {
	URL string
} {
	var calls []struct {
		URL string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Upload calls UploadFunc.
func (mock *FileStoreMock) Upload(r io.Reader) (string, error) {
	if mock.UploadFunc == nil {
		panic("FileStoreMock.UploadFunc: method is nil but FileStore.Upload was just called")
	}
	callInfo := struct {
		R io.Reader
	}{
		R: r,
	}
	mock.lockUpload.Lock()
	mock.calls.Upload = append(mock.calls.Upload, callInfo)
	mock.lockUpload.Unlock()
	return mock.UploadFunc(r)
}

// UploadCalls gets all the calls that were made to Upload.
// Check the length with:
//
//	len(mockedFileStore.UploadCalls())
func (mock *FileStoreMock) UploadCalls() []struct {
	R io.Reader
} {
	var calls []struct {
		R io.Reader
	}
	mock.lockUpload.RLock()
	calls = mock.calls.Upload
	mock.lockUpload.RUnlock()
	return calls
}
