// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ernado/lilith"
	"sync"
)

// Ensure, that ImageGeneratorMock does implement lilith.ImageGenerator.
// If this is not the case, regenerate this file with moq.
var _ lilith.ImageGenerator = &ImageGeneratorMock{}

// ImageGeneratorMock is a mock implementation of lilith.ImageGenerator.
//
//	func TestSomethingThatUsesImageGenerator(t *testing.T) {
//
//		// make and configure a mocked lilith.ImageGenerator
//		mockedImageGenerator := &ImageGeneratorMock{
//			GenerateFunc: func(ctx context.Context, req lilith.ImageRequest) ([]lilith.GeneratedImage, error) {
//				panic("mock out the Generate method")
//			},
//		}
//
//		// use mockedImageGenerator in code that requires lilith.ImageGenerator
//		// and then make assertions.
//
//	}
type ImageGeneratorMock struct {
	// GenerateFunc mocks the Generate method.
	GenerateFunc func(ctx context.Context, req lilith.ImageRequest) ([]lilith.GeneratedImage, error)

	// calls tracks calls to the methods.
	calls struct {
		// Generate holds details about calls to the Generate method.
		Generate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req lilith.ImageRequest
		}
	}
	lockGenerate sync.RWMutex
}

// Generate calls GenerateFunc.
func (mock *ImageGeneratorMock) Generate(ctx context.Context, req lilith.ImageRequest) ([]lilith.GeneratedImage, error) {
	if mock.GenerateFunc == nil {
		panic("ImageGeneratorMock.GenerateFunc: method is nil but ImageGenerator.Generate was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req lilith.ImageRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockGenerate.Lock()
	mock.calls.Generate = append(mock.calls.Generate, callInfo)
	mock.lockGenerate.Unlock()
	return mock.GenerateFunc(ctx, req)
}

// GenerateCalls gets all the calls that were made to Generate.
// Check the length with:
//
//	len(mockedImageGenerator.GenerateCalls())
func (mock *ImageGeneratorMock) GenerateCalls() []struct {
	Ctx context.Context
	Req lilith.ImageRequest
} {
	var calls []struct {
		Ctx context.Context
		Req lilith.ImageRequest
	}
	mock.lockGenerate.RLock()
	calls = mock.calls.Generate
	mock.lockGenerate.RUnlock()
	return calls
}
