// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ernado/lilith"
	"sync"
)

// Ensure, that MemoryMock does implement lilith.Memory.
// If this is not the case, regenerate this file with moq.
var _ lilith.Memory = &MemoryMock{}

// MemoryMock is a mock implementation of lilith.Memory.
//
//	func TestSomethingThatUsesMemory(t *testing.T) {
//
//		// make and configure a mocked lilith.Memory
//		mockedMemory := &MemoryMock{
//			MaintainFunc: func(ctx context.Context, chatID int64, msg lilith.Message) error {
//				panic("mock out the Maintain method")
//			},
//			NotesFunc: func(ctx context.Context, chatID int64) ([]lilith.ChatNote, error) {
//				panic("mock out the Notes method")
//			},
//		}
//
//		// use mockedMemory in code that requires lilith.Memory
//		// and then make assertions.
//
//	}
type MemoryMock struct {
	// MaintainFunc mocks the Maintain method.
	MaintainFunc func(ctx context.Context, chatID int64, msg lilith.Message) error

	// NotesFunc mocks the Notes method.
	NotesFunc func(ctx context.Context, chatID int64) ([]lilith.ChatNote, error)

	// calls tracks calls to the methods.
	calls struct {
		// Maintain holds details about calls to the Maintain method.
		Maintain []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// Msg is the msg argument value.
			Msg lilith.Message
		}
		// Notes holds details about calls to the Notes method.
		Notes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
		}
	}
	lockMaintain sync.RWMutex
	lockNotes    sync.RWMutex
}

// Maintain calls MaintainFunc.
func (mock *MemoryMock) Maintain(ctx context.Context, chatID int64, msg lilith.Message) error {
	if mock.MaintainFunc == nil {
		panic("MemoryMock.MaintainFunc: method is nil but Memory.Maintain was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ChatID int64
		Msg    lilith.Message
	}{
		Ctx:    ctx,
		ChatID: chatID,
		Msg:    msg,
	}
	mock.lockMaintain.Lock()
	mock.calls.Maintain = append(mock.calls.Maintain, callInfo)
	mock.lockMaintain.Unlock()
	return mock.MaintainFunc(ctx, chatID, msg)
}

// MaintainCalls gets all the calls that were made to Maintain.
// Check the length with:
//
//	len(mockedMemory.MaintainCalls())
func (mock *MemoryMock) MaintainCalls() []struct {
	Ctx    context.Context
	ChatID int64
	Msg    lilith.Message
} {
	var calls []struct {
		Ctx    context.Context
		ChatID int64
		Msg    lilith.Message
	}
	mock.lockMaintain.RLock()
	calls = mock.calls.Maintain
	mock.lockMaintain.RUnlock()
	return calls
}

// Notes calls NotesFunc.
func (mock *MemoryMock) Notes(ctx context.Context, chatID int64) ([]lilith.ChatNote, error) {
	if mock.NotesFunc == nil {
		panic("MemoryMock.NotesFunc: method is nil but Memory.Notes was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ChatID int64
	}{
		Ctx:    ctx,
		ChatID: chatID,
	}
	mock.lockNotes.Lock()
	mock.calls.Notes = append(mock.calls.Notes, callInfo)
	mock.lockNotes.Unlock()
	return mock.NotesFunc(ctx, chatID)
}

// NotesCalls gets all the calls that were made to Notes.
// Check the length with:
//
//	len(mockedMemory.NotesCalls())
func (mock *MemoryMock) NotesCalls() []struct {
	Ctx    context.Context
	ChatID int64
} {
	var calls []struct {
		Ctx    context.Context
		ChatID int64
	}
	mock.lockNotes.RLock()
	calls = mock.calls.Notes
	mock.lockNotes.RUnlock()
	return calls
}
