// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ernado/lilith"
	"sync"
)

// Ensure, that ScraperMock does implement lilith.Scraper.
// If this is not the case, regenerate this file with moq.
var _ lilith.Scraper = &ScraperMock{}

// ScraperMock is a mock implementation of lilith.Scraper.
//
//	func TestSomethingThatUsesScraper(t *testing.T) {
//
//		// make and configure a mocked lilith.Scraper
//		mockedScraper := &ScraperMock{
//			ScrapeFunc: func(ctx context.Context, url string) (*lilith.ScrapeResult, error) {
//				panic("mock out the Scrape method")
//			},
//		}
//
//		// use mockedScraper in code that requires lilith.Scraper
//		// and then make assertions.
//
//	}
type ScraperMock struct {
	// ScrapeFunc mocks the Scrape method.
	ScrapeFunc func(ctx context.Context, url string) (*lilith.ScrapeResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// Scrape holds details about calls to the Scrape method.
		Scrape []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// URL is the url argument value.
			URL string
		}
	}
	lockScrape sync.RWMutex
}

// Scrape calls ScrapeFunc.
func (mock *ScraperMock) Scrape(ctx context.Context, url string) (*lilith.ScrapeResult, error) {
	if mock.ScrapeFunc == nil {
		panic("ScraperMock.ScrapeFunc: method is nil but Scraper.Scrape was just called")
	}
	callInfo := struct {
		Ctx context.Context
		URL string
	}{
		Ctx: ctx,
		URL: url,
	}
	mock.lockScrape.Lock()
	mock.calls.Scrape = append(mock.calls.Scrape, callInfo)
	mock.lockScrape.Unlock()
	return mock.ScrapeFunc(ctx, url)
}

// ScrapeCalls gets all the calls that were made to Scrape.
// Check the length with:
//
//	len(mockedScraper.ScrapeCalls())
func (mock *ScraperMock) ScrapeCalls() []struct {
	Ctx context.Context
	URL string
} {
	var calls []struct {
		Ctx context.Context
		URL string
	}
	mock.lockScrape.RLock()
	calls = mock.calls.Scrape
	mock.lockScrape.RUnlock()
	return calls
}
