// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ernado/lilith"
	"sync"
)

// Ensure, that WeatherProviderMock does implement lilith.WeatherProvider.
// If this is not the case, regenerate this file with moq.
var _ lilith.WeatherProvider = &WeatherProviderMock{}

// WeatherProviderMock is a mock implementation of lilith.WeatherProvider.
//
//	func TestSomethingThatUsesWeatherProvider(t *testing.T) {
//
//		// make and configure a mocked lilith.WeatherProvider
//		mockedWeatherProvider := &WeatherProviderMock{
//			CurrentFunc: func(ctx context.Context, city string, countryCode string) (*lilith.WeatherReport, error) {
//				panic("mock out the Current method")
//			},
//		}
//
//		// use mockedWeatherProvider in code that requires lilith.WeatherProvider
//		// and then make assertions.
//
//	}
type WeatherProviderMock struct {
	// CurrentFunc mocks the Current method.
	CurrentFunc func(ctx context.Context, city string, countryCode string) (*lilith.WeatherReport, error)

	// calls tracks calls to the methods.
	calls struct {
		// Current holds details about calls to the Current method.
		Current []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// City is the city argument value.
			City string
			// CountryCode is the countryCode argument value.
			CountryCode string
		}
	}
	lockCurrent sync.RWMutex
}

// Current calls CurrentFunc.
func (mock *WeatherProviderMock) Current(ctx context.Context, city string, countryCode string) (*lilith.WeatherReport, error) {
	if mock.CurrentFunc == nil {
		panic("WeatherProviderMock.CurrentFunc: method is nil but WeatherProvider.Current was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		City        string
		CountryCode string
	}{
		Ctx:         ctx,
		City:        city,
		CountryCode: countryCode,
	}
	mock.lockCurrent.Lock()
	mock.calls.Current = append(mock.calls.Current, callInfo)
	mock.lockCurrent.Unlock()
	return mock.CurrentFunc(ctx, city, countryCode)
}

// CurrentCalls gets all the calls that were made to Current.
// Check the length with:
//
//	len(mockedWeatherProvider.CurrentCalls())
func (mock *WeatherProviderMock) CurrentCalls() []struct {
	Ctx         context.Context
	City        string
	CountryCode string
} {
	var calls []struct {
		Ctx         context.Context
		City        string
		CountryCode string
	}
	mock.lockCurrent.RLock()
	calls = mock.calls.Current
	mock.lockCurrent.RUnlock()
	return calls
}
