name: 'Dependency Review'

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    env:
      FIRST_COMMIT_SHA: 373136b44c15fc85829abf2d86ee59d60b734d11
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v6
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v5
        with:
          head-ref: HEAD
          base-ref: "${{ env.FIRST_COMMIT_SHA }}"
          config-file: './.github/dependency-review-config.yml'
